version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - mynetwork

  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.0-fpm
    volumes:
      - ./:/var/www/
    depends_on:
      - db
    networks:
      - mynetwork


  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbname
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8888:80"
    networks:
      - mynetwork
volumes:
  db-data:

networks:
  mynetwork:
    driver: bridge